FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo
RUN make -f Makefile.daomake linux INSTALL=/install
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
